const developmentsData = [
  {
    number: dev0,
    name: 'Leadership',
    cost: 10,
    points: 2,
    effect: 'Reroll 1 die (after last roll)'
  },
  {
    number: dev1,
    name: 'Irrigation',
    cost: 10,
    points: 2,
    effect: '2 skulls has no effect',
  },
  {
    number: dev2,
    name: 'Agriculture',
    cost: 15,
    points: 3,
    effect: '+1 food per food die',
  },
  {
    number: dev3,
    name: 'Quarrying',
    cost: 15,
    points: 3,
    effect: '+1 stone if collecting stone',
  },
  {
    number: dev4,
    name: 'Medicine',
    cost: 15,
    points: 3,
    effect: '3 skulls has no effect',
  },
  {
    number: dev5,
    name: 'Coinage',
    cost: 20,
    points: 4,
    effect: 'coin die worth 12',
  },
  {
    number: dev6,
    name: 'Caravans',
    cost: 20,
    points: 4,
    effect: 'do not need to discard goods',
  },
  {
    number: dev7,
    name: 'Religion',
    cost: 20,
    points: 6,
    effect: '5+ skulls affects opponents',
  },
  {
    number: dev8,
    name: 'Granaries',
    cost: 30,
    points: 6,
    effect: 'sell food for 4 coins each',
  },
  {
    number: dev9,
    name: 'Masonry',
    cost: 30,
    points: 6,
    effect: '+1 worker per worker die',
  },
  {
    number: dev10,
    name: 'Engineering',
    cost: 40,
    points: 6,
    effect: 'use stone for 3 workers each',
  },
  {
    number: dev11,
    name: 'Architecture',
    cost: 50,
    points: 8,
    effect: '+1 point per monument',
  },
  {
    number: dev12,
    name: 'Empire',
    cost: 60,
    points: 8,
    effect: '+1 point per city',
  },
];

module.exports = developmentsData;